apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ova-ingress
  namespace: ova
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.ova.app
        - app.ova.app
        - admin.ova.app
      secretName: ova-tls
  rules:
    - host: api.ova.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-banking
                port:
                  number: 8080
    - host: app.ova.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: admin.ova.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-console
                port:
                  number: 3001
