-- V015: Critical security and consistency fixes for settlement and FX flows

-- 1) Outbox publish timestamp used by blockchain outbox poller
ALTER TABLE shared.outbox_events
    ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;

-- 2) Expand FX quotes schema to align payments and FX modules
ALTER TABLE payments.fx_quotes
    ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS fee_amount NUMERIC(20, 8) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fee_currency TEXT,
    ADD COLUMN IF NOT EXISTS mid_market_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS customer_rate NUMERIC(20, 10),
    ADD COLUMN IF NOT EXISTS status TEXT,
    ADD COLUMN IF NOT EXISTS consumed_at TIMESTAMPTZ;

UPDATE payments.fx_quotes
SET exchange_rate = COALESCE(exchange_rate, customer_rate, rate),
    customer_rate = COALESCE(customer_rate, rate),
    mid_market_rate = COALESCE(
        mid_market_rate,
        CASE
            WHEN spread IS NOT NULL
             AND (1 - spread) <> 0
             AND COALESCE(customer_rate, rate) IS NOT NULL
            THEN COALESCE(customer_rate, rate) / (1 - spread)
            ELSE COALESCE(mid_market_rate, customer_rate, rate)
        END
    ),
    fee_amount = COALESCE(fee_amount, 0),
    fee_currency = COALESCE(fee_currency, target_currency),
    status = COALESCE(
        status,
        CASE
            WHEN used THEN 'consumed'
            WHEN expires_at < NOW() THEN 'expired'
            ELSE 'active'
        END
    );

CREATE INDEX IF NOT EXISTS idx_fx_quotes_status_expires
    ON payments.fx_quotes(status, expires_at DESC);

-- 3) Conversion history table required by FX conversion service
CREATE TABLE IF NOT EXISTS payments.fx_conversions (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_id             UUID NOT NULL REFERENCES payments.fx_quotes(id),
    transaction_id       UUID NOT NULL REFERENCES ledger.transactions(id),
    user_id              UUID NOT NULL REFERENCES identity.users(id),
    source_account_id    UUID NOT NULL REFERENCES ledger.accounts(id),
    target_account_id    UUID NOT NULL REFERENCES ledger.accounts(id),
    source_currency      TEXT NOT NULL,
    target_currency      TEXT NOT NULL,
    source_amount        NUMERIC(20, 8) NOT NULL,
    target_amount        NUMERIC(20, 8) NOT NULL,
    customer_rate        NUMERIC(20, 10) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fx_conversions_quote
    ON payments.fx_conversions(quote_id);

CREATE INDEX IF NOT EXISTS idx_fx_conversions_user_created
    ON payments.fx_conversions(user_id, created_at DESC);

-- 4) Allow safeguarding discrepancy alerts generated by reconciliation
ALTER TABLE shared.threshold_alerts DROP CONSTRAINT IF EXISTS chk_alert_type;

ALTER TABLE shared.threshold_alerts
    ADD CONSTRAINT chk_alert_type CHECK (
        alert_type IN (
            'SINGLE_TRANSACTION',
            'DAILY_CUMULATIVE',
            'WEEKLY_CUMULATIVE',
            'VELOCITY',
            'STRUCTURING',
            'GEOGRAPHIC',
            'BEHAVIORAL',
            'SAFEGUARDING_DISCREPANCY'
        )
    );
